platform :ios, '7.0'

pod 'EAIntroView'
pod 'Facebook-iOS-SDK'
pod 'FormatterKit'
pod 'JTCalendar'
pod 'M13ProgressSuite'
pod 'RestKit'
pod 'SDWebImage'
pod 'TLYShyNavBar'
pod 'WeiboSDK'
pod 'Weixin'
